services:
  app1:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8081:8080"

  app2:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8082:8080"

  app3:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8083:8080"

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
  
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasource