services:
  app-1:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8081:8080"

  app-2:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8082:8080"

  app-3:
    image: ghcr.io/upa-io/helidon-chassis-java:latest
    cpus: '0.99'
    mem_limit: 200M
    ports:
      - "8083:8080"